// Generated by scripts/fetch_photos.py. Do not edit by hand.

export const photoAssets: Record<string, number> = {
  'american-crow': require('../../assets/photos/american-crow.jpg'),
  'american-robin': require('../../assets/photos/american-robin.jpg'),
  'blue-jay': require('../../assets/photos/blue-jay.jpg'),
  'chimney-swift': require('../../assets/photos/chimney-swift.jpg'),
  'dark-eyed-junco': require('../../assets/photos/dark-eyed-junco.jpg'),
  'eastern-gray-squirrel': require('../../assets/photos/eastern-gray-squirrel.jpg'),
  'european-starling': require('../../assets/photos/european-starling.jpg'),
  'herring-gull': require('../../assets/photos/herring-gull.jpg'),
  'house-sparrow': require('../../assets/photos/house-sparrow.jpg'),
  'monarch': require('../../assets/photos/monarch.jpg'),
  'moths': require('../../assets/photos/moths.jpg'),
  'mourning-dove': require('../../assets/photos/mourning-dove.jpg'),
  'raccoon': require('../../assets/photos/raccoon.jpg'),
  'red-tailed-hawk': require('../../assets/photos/red-tailed-hawk.jpg'),
  'rock-pigeon': require('../../assets/photos/rock-pigeon.jpg'),
  'virginia-opossum': require('../../assets/photos/virginia-opossum.jpg'),
  'white-throated-sparrow': require('../../assets/photos/white-throated-sparrow.jpg'),
};
