// Generated by scripts/build_soundscapes.py. Do not edit by hand.

export const soundAssets: Record<string, number> = {
  'dawn-chorus': require('../../assets/sounds/dawn-chorus.m4a'),
  'day-birds': require('../../assets/sounds/day-birds.m4a'),
  'dusk-birds': require('../../assets/sounds/dusk-birds.m4a'),
  'summer-dusk': require('../../assets/sounds/summer-dusk.m4a'),
  'summer-night': require('../../assets/sounds/summer-night.m4a'),
  'fall-day': require('../../assets/sounds/fall-day.m4a'),
  'fall-dusk': require('../../assets/sounds/fall-dusk.m4a'),
  'fall-night': require('../../assets/sounds/fall-night.m4a'),
  'winter-day': require('../../assets/sounds/winter-day.m4a'),
  'quiet-night': require('../../assets/sounds/quiet-night.m4a'),
  'harbor': require('../../assets/sounds/harbor.m4a'),
  'harbor-night': require('../../assets/sounds/harbor-night.m4a'),
  'rain': require('../../assets/sounds/rain.m4a'),
  'wind': require('../../assets/sounds/wind.m4a'),
  'snow': require('../../assets/sounds/snow.m4a'),
};
