// Generated by scripts/build_soundscapes.py. Do not edit by hand.

export const soundAssets: Record<string, number> = {
  'waterfront-day': require('../../assets/sounds/waterfront-day.m4a'),
  'waterfront-night': require('../../assets/sounds/waterfront-night.m4a'),
  'park-day': require('../../assets/sounds/park-day.m4a'),
  'park-night': require('../../assets/sounds/park-night.m4a'),
  'block-day': require('../../assets/sounds/block-day.m4a'),
  'block-night': require('../../assets/sounds/block-night.m4a'),
  'waterfront-winter-night': require('../../assets/sounds/waterfront-winter-night.m4a'),
  'park-winter-night': require('../../assets/sounds/park-winter-night.m4a'),
  'block-winter-night': require('../../assets/sounds/block-winter-night.m4a'),
  'rain': require('../../assets/sounds/rain.m4a'),
};
