// Generated by scripts/build_soundscapes.py. Do not edit by hand.

export const soundAssets: Record<string, number> = {
  'waterfront': require('../../assets/sounds/waterfront.m4a'),
  'park': require('../../assets/sounds/park.m4a'),
  'block': require('../../assets/sounds/block.m4a'),
  'rain': require('../../assets/sounds/rain.m4a'),
};
